name: Python CI with Coverage and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov coverage flake8

    - name: Run tests with coverage
      run: pytest --cov=Calc --cov-report=term-missing

    - name: Run static analysis
      run: flake8 Calc.py test_calc.py
